### ISSUE TITLE
net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by MingyuJeon** [pubnub/pubnub-angular2#14]
It works well at first, but it makes an error soon.
Even though, it has an error, still works.

I think this part is one of the reason.

```
self.broadcaster.emitError(received);
            } else {
              received.affectedChannels.forEach((channel) => {
                if (self.broadcastChannels[channel] && self.broadcastChannels[channel].includes(event)) {
                  self.broadcaster.emit(event, channel, received);
                }
              });

```

I'm using typescript version 2.0.10 and angular-cli beta24.

<img width="1440" alt="2017-02-14 2 04 15" src="https://cloud.githubusercontent.com/assets/15281293/22893742/fb4d5b0e-f259-11e6-9adf-798dae46a73e.png">

**Comment by ManuelFernando** [comment]
Thanks, @MingyuJeon I’ll check it.

**Comment by ManuelFernando** [comment]
@MingyuJeon I’m checking this but I need some of your help, can you put this code “console.log(received);” in the file ’node_modules/pubnub-angular2/dist/pubnub-angular2.js” after line  602 and share me the console message.

**Comment by MingyuJeon** [comment]
I added it, but I couldn't get any messages on the console.
Still same issue

**Comment by ManuelFernando** [comment]
thanks, please try to put this over the line 600 and if this doesn’t till work then in the 587.

**Comment by MingyuJeon** [comment]
Still I cannot see anything. :(

![image](https://cloud.githubusercontent.com/assets/15281293/23055838/5f379d2c-f52b-11e6-9390-0a848e5d6f72.png)

**Comment by ManuelFernando** [comment]
@MingyuJeon thanks for trying again! I don’t know if it possible that you allow me the snippet of code that you are using, name of channels, example of messages with your keys, we have identified the point to fix but if it’s a good idea to know internally what is happening!

if you can share me this, please send me to manuel@pubnub.com, this is way we can help you as fast as we can.

**Comment by MingyuJeon** [comment]
@ManuelFernando Sorry for the reply.
I think it was version issue.
I updated angular-cli and reinstalled all of npm packages in node_modules.
And the error's gone :)

**Comment by ManuelFernando** [comment]
@MingyuJeon perfect.. I’m glad to hear that!
