### ISSUE TITLE
Pubnub-angular2 with Angular CLI

### ISSUE THREAD

**Issue by tripstar22** [pubnub/pubnub-angular2#16]
I have my Angular CLI environment set up and I would like to incorporate Pubnub-angular2 into my project. This has been difficult because Angular CLI does not have a `systemjs.config.js` file in the project. 

Angular CLI moved the build system from SystemJS to Webpack in [1.0.0-beta.11](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta11-webpack-2016-08-02). So obviously when I add the markup below I get an error `Uncaught ReferenceError: System is not defined`. 

What is a good work-around for this issue? I am currently using Angular CLI version 1.0.0-beta.30. Thanks :)

```<script>
    System.import('app').catch(function(err){ 
        console.error(err);
    });
</script>

**Comment by ManuelFernando** [comment]
Hi @tripstar22, thanks for using PubNub-Angular2 SDK

1. Add pubnub javascript from CDN to your index.html
<script src=“https://cdn.pubnub.com/sdk/javascript/pubnub.4.4.4.js"></script>

2. Add pubnub-angular2 from NPM

3. Omit the step of adding the reference to SystemJS

4. Import PubNubAngular in your angular module and components, Angular CLI will do the rest.

5. Inject the PubNubAngular in the constructor of your component.

6. Init your instance.

We hope that this can help you and also other people!

**Comment by tripstar22** [comment]
@ManuelFernando thanks for the help! Much appreciated!
