### ISSUE TITLE
SyntaxError: Use of reserved word 'class' on Safari browser

### ISSUE THREAD

**Issue by hoangdo86** [pubnub/pubnub-angular2#17]
First of all, I want to say thank you very much for publishing this SDK. It's very helpful. 

I'm getting an issue on Safari browser when running pubnub-angular2 with Webpack + Angular2 (AoT), The issue can be reproduced by start this GIT project (https://github.com/ManuelFernando/PubNub-Angular2-Demo-CLI) and browse the page on Safari browser.

Thanks
Do

**Comment by ManuelFernando** [comment]
Hi @hoangdo86 we are glad to hear that pubnub-angular2 fit your needs and helpful for you! 👍 
in other hand we couldn’t reproduce this issue, we test on safari 10.0.3 and the latest version of Angular CLI
