### ISSUE TITLE
Trying to use pubnub-angular in Angular4 project

### ISSUE THREAD

**Issue by PepeBel4** [pubnub/pubnub-angular2#26]
I followed PubNub's tutorizal for Realtime apps, but when compiling see following issue:

ERROR in ./node_modules/pubnub-angular2/lib/pubnub-angular4.js
Module not found: Error: Can't resolve 'pubnub' in '/Users/pascalpeeters/Documents/GitHub/your-race-fe/node_modules/pubnub-angular2/lib'
 @ ./node_modules/pubnub-angular2/lib/pubnub-angular4.js 8:14-31
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
       4 modules
webpack: Failed to compile.

Anyone could guide me where I go wrong?

**Comment by namnn** [comment]
I actually have the same issue
